# Generated by Django 4.1.13 on 2024-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
